# Generated by Django 4.0.5 on 2022-07-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_instrument_instrument_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_photo',
        ),
    ]
